#!/bin/bash


if (($# == 0)) 
then 
	for file in *
	do
		if [ -s $file ]
		then
			echo "$file"
		fi	
	done
	
else
	for x in "$@"
	do
		if [ -d "$x" ]
		then
			for file in "$x"/*
			do
				if [  -s $file ]
				then
					echo "$file"
				fi	
			done
		fi
	
	done
fi 
